=== kurt-hectic/oscar-client/oscar_lib/static/xml-schemas/simplestation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2019 (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="country">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="TZA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="elevation" type="xs:float"/>
	<xs:element name="endHour" type="xs:byte"/>
	<xs:element name="endMinute" type="xs:byte"/>
	<xs:element name="endMonth" type="xs:byte"/>
	<xs:element name="endWeekday" type="xs:byte"/>
	<xs:element name="established" type="xs:date"/>
	<xs:element name="international" type="xs:boolean"/>
	<xs:element name="interval" type="xs:int"/>
	<xs:element name="latitude" type="xs:float"/>
	<xs:element name="longitude" type="xs:float"/>
	<xs:element name="timezone" type="xs:string"/>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="url" type="xs:anyURI"/>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="stationtype" type="xs:string"/>
	


	<xs:element name="observation">
		<xs:complexType>
			<xs:all>
				<xs:element ref="variable"/>
				<xs:element ref="observationsource"/>
				<xs:element ref="affiliation"/>
				<xs:element ref="schedule"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="affiliations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="affiliation" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="observations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="observation" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="observationsource" type="xs:string"/>
	<xs:element name="region">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Africa"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="schedule">
		<xs:complexType>
			<xs:all>
				<xs:element ref="startMonth"/>
				<xs:element ref="endMonth"/>
				<xs:element ref="startWeekday"/>
				<xs:element ref="endWeekday"/>
				<xs:element ref="startHour"/>
				<xs:element ref="endHour"/>
				<xs:element ref="startMinute"/>
				<xs:element ref="endMinute"/>
				<xs:element ref="interval"/>
				<xs:element ref="international"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="startHour" type="xs:byte"/>
	<xs:element name="startMinute" type="xs:byte"/>
	<xs:element name="startMonth" type="xs:byte"/>
	<xs:element name="startWeekday" type="xs:byte"/>
	<xs:element name="station">
		<xs:complexType>
			<xs:all>
				<xs:element ref="name"/>
				<xs:element ref="wigosid"/>
				<xs:element ref="latitude"/>
				<xs:element ref="longitude"/>
				<xs:element ref="elevation"/>
				<xs:element ref="country"/>
				<xs:element ref="established"/>
				<xs:element ref="region"/>
				<xs:element ref="affiliations"/>				
				<xs:element ref="observations"/>
				<xs:element ref="url" minOccurs="0"/>
				<xs:element ref="description" minOccurs="0"/>
				<xs:element ref="timezone" minOccurs="0"/>
				<xs:element ref="stationtype"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="variable" type="xs:short"/>	
	<xs:element name="affiliation" type="xs:string"/>
	<xs:element name="wigosid">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d+-\d+-\d+-\w{1,6}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== kurt-hectic/oscar-client/tests/stationinfo.xml
<station xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/Timo/Documents/git/oscar-lib/oscar_lib/static/xml-schemas/simplestation.xsd">
	<name>Novo Aripuan√£</name>
	<wigosid>0-76-0-1303304000000594</wigosid>
	<latitude>-5.141139</latitude>
	<longitude>-60.380531000000005</longitude>
	<elevation>45.0</elevation>
	<country>BRA</country>
	<established>2019-07-18</established>
	<region>southAmerica</region>
	<urls>
		<url>https://test.de</url>
		<url>https://test.de/2</url>
	</urls>
	<observations>
		<observation>
			<variable>224</variable>
			<observationsource>automaticReading</observationsource>
			<affiliation>GOS</affiliation>
			<schedule>
				<startMonth>1</startMonth>
				<endMonth>12</endMonth>
				<startWeekday>1</startWeekday>
				<endWeekday>7</endWeekday>
				<startHour>0</startHour>
				<endHour>23</endHour>
				<startMinute>0</startMinute>
				<endMinute>59</endMinute>
				<interval>3600</interval>
				<international>true</international>
				<real-time>true</real-time>
			</schedule>
		</observation>
		<observation>
			<variable>251</variable>
			<observationsource>automaticReading</observationsource>
			<affiliation>GOS</affiliation>
			<schedule>
				<startMonth>1</startMonth>
				<endMonth>12</endMonth>
				<startWeekday>1</startWeekday>
				<endWeekday>7</endWeekday>
				<startHour>0</startHour>
				<endHour>23</endHour>
				<startMinute>0</startMinute>
				<endMinute>59</endMinute>
				<interval>3600</interval>
				<international>true</international>
				<real-time>true</real-time>
			</schedule>
		</observation>
		<observation>
			<variable>225</variable>
			<observationsource>automaticReading</observationsource>
			<affiliation>GOS</affiliation>
			<schedule>
				<startMonth>1</startMonth>
				<endMonth>12</endMonth>
				<startWeekday>1</startWeekday>
				<endWeekday>7</endWeekday>
				<startHour>0</startHour>
				<endHour>23</endHour>
				<startMinute>0</startMinute>
				<endMinute>59</endMinute>
				<interval>3600</interval>
				<international>true</international>
				<real-time>true</real-time>
			</schedule>
		</observation>
		<observation>
			<variable>216</variable>
			<observationsource>automaticReading</observationsource>
			<affiliation>GOS</affiliation>
			<schedule>
				<startMonth>1</startMonth>
				<endMonth>12</endMonth>
				<startWeekday>1</startWeekday>
				<endWeekday>7</endWeekday>
				<startHour>0</startHour>
				<endHour>23</endHour>
				<startMinute>0</startMinute>
				<endMinute>59</endMinute>
				<interval>3600</interval>
				<international>true</international>
				<real-time>true</real-time>
			</schedule>
		</observation>
		<observation>
			<variable>12005</variable>
			<observationsource>automaticReading</observationsource>
			<affiliation>GOS</affiliation>
			<schedule>
				<startMonth>1</startMonth>
				<endMonth>12</endMonth>
				<startWeekday>1</startWeekday>
				<endWeekday>7</endWeekday>
				<startHour>0</startHour>
				<endHour>23</endHour>
				<startMinute>0</startMinute>
				<endMinute>59</endMinute>
				<interval>3600</interval>
				<international>true</international>
				<real-time>true</real-time>
			</schedule>
		</observation>
		<observation>
			<variable>12006</variable>
			<observationsource>automaticReading</observationsource>
			<affiliation>GOS</affiliation>
			<schedule>
				<startMonth>1</startMonth>
				<endMonth>12</endMonth>
				<startWeekday>1</startWeekday>
				<endWeekday>7</endWeekday>
				<startHour>0</startHour>
				<endHour>23</endHour>
				<startMinute>0</startMinute>
				<endMinute>59</endMinute>
				<interval>3600</interval>
				<international>true</international>
				<real-time>true</real-time>
			</schedule>
		</observation>
		<observation>
			<variable>572</variable>
			<observationsource>automaticReading</observationsource>
			<affiliation>GOS</affiliation>
			<schedule>
				<startMonth>1</startMonth>
				<endMonth>12</endMonth>
				<startWeekday>1</startWeekday>
				<endWeekday>7</endWeekday>
				<startHour>0</startHour>
				<endHour>23</endHour>
				<startMinute>0</startMinute>
				<endMinute>59</endMinute>
				<interval>3600</interval>
				<international>true</international>
				<real-time>true</real-time>
			</schedule>
		</observation>
		<observation>
			<variable>210</variable>
			<observationsource>automaticReading</observationsource>
			<affiliation>GOS</affiliation>
			<schedule>
				<startMonth>1</startMonth>
				<endMonth>12</endMonth>
				<startWeekday>1</startWeekday>
				<endWeekday>7</endWeekday>
				<startHour>0</startHour>
				<endHour>23</endHour>
				<startMinute>0</startMinute>
				<endMinute>59</endMinute>
				<interval>3600</interval>
				<international>true</international>
				<real-time>true</real-time>
			</schedule>
		</observation>
	</observations>
	<stationtype>landFixed</stationtype>
	<status>operational</status>
	<description>Automatic weather station</description>
	<timezone>UTC-4</timezone>
	<organization>INMET</organization>
	<affiliations>
		<affiliation>GOS</affiliation>
		<affiliation>GOS</affiliation>
		<affiliation>GOS</affiliation>
		<affiliation>GOS</affiliation>
		<affiliation>GOS</affiliation>
		<affiliation>GOS</affiliation>
		<affiliation>GOS</affiliation>
		<affiliation>GOS</affiliation>
	</affiliations>
</station>
